### ISSUE TITLE
Is it possible to increase the mininum time between the events to avoid cheating?

### ISSUE THREAD

**Issue by acobo** [FMCorz/moodle-block_xp#10]
Hello,
 I have started to use this great block in several courses, and soon we had some students just clicking in the same items again and again. I would like to increase the minimun time between events. Is it possible to change its value without re-installing this module by the site administrator?
 thank you in advance,
  Adolfo.

**Comment by jbourdon** [comment]
I also have students doing the same thing. Refreshing their page seems to be the method of choice.

**Comment by FMCorz** [comment]
Students can refresh a page but only every 30 seconds, I thought that'd discourage them but apparently not. I will try to improve this today.

**Comment by FMCorz** [comment]
I have worked on a solution which does the following:

- Still limited per session, a student can open multiple sessions to double XP.
- A certain amount of actions is limited in a given time, hence a students opening all the pages of the course at once will only be rewarded for the n first ones.
- Two identical actions cannot happen within a given time, refreshing a page will not work for a longer time than before.

The values can be set in the plugin settings.

Of course students will try to find other ways to cheat, but this is already an improvement that should not affect non-cheating users.

**Comment by acobo** [comment]
Thankyou!
 it is really helpful, because our students are using this "trick" and it takes for us a lot of time to discover and fix. 
We will try and see.
Thanks again,
  Adolfo.

**Comment by jbourdon** [comment]
Thanks very much for doing this. This should be a great addition to the plugin.

**Comment by FMCorz** [comment]
No worries, this will come in the next version.

Linking with #6.
