### ISSUE TITLE
Cannot translate Plus-tab in Moodle language pack

### ISSUE THREAD

**Issue by Urpokarhu1** [FMCorz/moodle-block_xp#100]
Hello,

It seems you cannot translate Plus-tab in Moodle language pack

**Comment by FMCorz** [comment]
That is true and intentional. We did not want to put the burden of translating promotional material on the community, especially considering how frequently it could be changed and be reworded. Our website itself is also only available in English at present, so it is consistent with that page.

**Comment by FMCorz** [comment]
Closing for the reasons expressed above.
