### ISSUE TITLE
Controller for route not found

### ISSUE THREAD

**Issue by bbw-ki** [FMCorz/moodle-block_xp#101]
Moodle-Site is on Version 3.7.2

Error when clicking Rating

Controller for route not found.

× Debug info: 
Error code: codingerror 

× Stack trace: •line 95 of \blocks\xp\classes\local\routing\router.php: coding_exception thrown
•line 79 of \blocks\xp\classes\local\routing\router.php: call to block_xp\local\routing\router->get_controller_from_request()
•line 38 of \blocks\xp\index.php: call to block_xp\local\routing\router->dispatch()

**Comment by FMCorz** [comment]
Hi @bbw-ki, the solution should be found in this page: https://levelup.branchup.tech/docs/article/error-controller-for-route-not-found. Thank you
