### ISSUE TITLE
Wrong column name in classes/output/log_table.php

### ISSUE THREAD

**Issue by wiktorwandachowicz** [FMCorz/moodle-block_xp#104]
Cannot sort by **Reward** column in 'Log' view.

There is in `function __construct()` of `log_table.php`:
```
        // Define columns.
        $this->define_columns(array(
            'time',
            'fullname',
            'reward',
            'eventname'
        ))
```

But there is a typo: instead of `'reward'` it should be `'xp'` (just like in column definition in the DB).
Otherwise users get DBML exceptions while sorting the table over **Reward** column.

**Comment by FMCorz** [comment]
Thanks for the report!
