### ISSUE TITLE
Hide register logs

### ISSUE THREAD

**Issue by goggo24** [FMCorz/moodle-block_xp#105]
Is there a way to hide the register logs for teachers? In our instance they are not allowed to see logfiles from students. I haven't found any admin-setting or capability in this direction. 
Have I missed something? If not, would you accept a pull request, where the display can be controlled via a capability?

**Comment by FMCorz** [comment]
Hi @goggo24,

You are right, users with the capability to _manage_ Level up! can see all of its pages. We would most definitely accept pull requests for a new capability. We imagine that "block/xp:viewlogs" could be a good fit, the latter should inherit from the manage capability, and be checked for in the log controllers.

Thank you!
Fred

**Comment by FMCorz** [comment]
This has been implemented and will be included in the next release. Thank you!
