### ISSUE TITLE
Behat failure report.feature

### ISSUE THREAD

**Issue by Rabecerra** [FMCorz/moodle-block_xp#109]
Hi guys,

It looks like this https://github.com/FMCorz/moodle-block_xp/blob/master/classes/output/report_table.php#L107 added atribute was causing a failure in report.feature behat test, due to no finding the _generaltable_ attribute for the table. Don't know if this is something is happening right now. I've used the latest version from https://moodle.org/plugins/block_xp.

Thanks for the help.

**Comment by FMCorz** [comment]
Well spotted! Thank you for reporting this, this has been fixed.
