### ISSUE TITLE
Specifiy a specific item for an event

### ISSUE THREAD

**Issue by acobo** [FMCorz/moodle-block_xp#11]
Hello,
 I would like to restrict the trigger of an event to a particular moodle item. I have noticed that rules can have "event_name" but also event component, action and target. How can I create a new rule that give points only if a particular moodle itemp has been read or updatge? is it implemented?
 Thank you in advance for your answer,
  Adolfo.

**Comment by FMCorz** [comment]
If by item you mean a specific forum or something like that, it is not supported yet.

**Comment by FMCorz** [comment]
Renamed this issue to match my understand where users would like to define rules for a matching activity, module or even maybe a context.
