### ISSUE TITLE
"Activity and material is" in rules are lost during export/import of Moodle Course

### ISSUE THREAD

**Issue by MarkusPiotrowski** [FMCorz/moodle-block_xp#110]
Our Moodle version is 3.4, at Ruhr-University Bochum, Germany. 
When copying a complete course by export/import (e.g. to setup a course for a new term) there is an issue with copying the rules. The section "Activity and material" is not copied correctly so that after the import the input field shows: Error: Unknown module (translated from German)

**Comment by FMCorz** [comment]
Hi @MarkusPiotrowski,

This seems related to an issue (#95) that we fixed a little wile ago. Would you please upgrade to the latest version, and confirm that the problem went away?

Thank you!

**Comment by MarkusPiotrowski** [comment]
Thank you. I don't have administrative access. Will ask our Moodle admin and will eventually report back. Feel free to close this if you like.

**Comment by FMCorz** [comment]
Closing, please reopen if this remains an issue.
