### ISSUE TITLE
Limit experience points

### ISSUE THREAD

**Issue by kiosnkof** [FMCorz/moodle-block_xp#112]
Can someone tell me how I can limit my experience points:

Example
I have a forum that gives me 5xp when the student participates, but if he / she participates again, they should not add 5xp. I only require you to add 1 time

If anyone can help me I will be grateful

**Comment by FMCorz** [comment]
Hi @kiosnkof 

The cheat guard will prevent repeated actions from counting more than once. Although the cheat guard from the free version may allow the actions to account after a period of time. If you need a strict cheat guard, please have a look at [Level up! Plus](https://levelup.plus).

Thank you!
