### ISSUE TITLE
No possibility to define rules

### ISSUE THREAD

**Issue by hsworms** [FMCorz/moodle-block_xp#117]
Hello,
yesterday we did a necessary security update for Moodle and since then no rule can be set or changed in "Level up!". In addition, I no longer see my rules for older courses.
We have the version 3.10.2 of Level Up and Moodle 3.9.5.
I hope they can help us out as the semester starts soon.
Thanks!

**Comment by FMCorz** [comment]
Hi @hsworms,

Thank you for the report.

- What do you mean that no rules can be changed? What are the symptoms?
- Would you be able to try with another theme?
- Have you turned debugging (from site admin > Development > Debugging) to DEVELOPER to see if errors were visible?
- Can you open the Web Console (Press Command+Option+J (Mac) or Control+Shift+J (Windows, Linux, Chrome OS) and share the messages on there?

Thank you!
Fred

**Comment by hsworms** [comment]
Thanks for the quick reply.

I can't see any rules anymore, by that I mean that on the "Rules" tab there is only the heading "Event Rules" and advertising for "Level Up +". Otherwise there is just a blank page now.

Debugging message: 
Fatal error: Cannot declare class mod_data\event\comment_deleted, because the name is already in use in /var/www/moodle/moodle/mod/hotquestion/classes/event/xxxcomment_created.php on line 0

Translated with www.DeepL.com/Translator (free version)

**Comment by FMCorz** [comment]
Thank you! This error indicates that the problem comes from the module `mod_hotquestion` that does something wrong. I'm afraid we cannot offer a workaround at this point, aside perhaps from deleting the file xxxcomment_created.php in the other plugin, but I would advise to ask their developers first.

**Comment by FMCorz** [comment]
Closing as caused by another plugin.
