### ISSUE TITLE
Users can edit other users profiles from the ladder.

### ISSUE THREAD

**Issue by easyflhomeschool** [FMCorz/moodle-block_xp#119]
I have a group of students who click on other students on the ladder and changed their photos and usernames.   Thankfully they only did this to their siblings and close friends, but they were able to access all member so the site.   How can this be restricted?   I can hide their identites, but that takes the fun out of the ladder.   How can I show the identities, but not allow them to access member profiles?

**Comment by FMCorz** [comment]
Thank you for your report.

_Level up!_ does not allow students to edit any other students information, even teachers themselves cannot use _Level up!_ to modify other student's pictures or names. There must be an issue in permissions allowing students to modify other accounts, we suggest that you revise the "edit:profile" capabilities.

**Comment by easyflhomeschool** [comment]
Will it still allow them to view each others profiles?

**Comment by easyflhomeschool** [comment]
I think I was able to lock it all down.  Thank you.
