### ISSUE TITLE
Leaderboard 

### ISSUE THREAD

**Issue by jbourdon** [FMCorz/moodle-block_xp#12]
For students who aren't at the top of the leaderboard, the board can have a negative effect. It can be discouraging to see exactly how impossible it will be for you to make it to the top of the board. One solution to this is to have a relative leaderboard where students only see the 5 people ahead of them and the 5 people below them. This will keep the user engaged as the ability to move up the leader board seems more attainable.  Having the option to switch between a absolute leader board (actual ranking in the course) and a relative lederboard (seeing those directly above and below you) would be a great addition.

**Comment by mouneyrac** [comment]
It's a nice subject. I thought about that too.

(personal opinion coming) I think block_xp still need to display a total ranking otherwise. When I am confronted to a near leaderboard it doesn't motivate me as I don't know what is the top of the ladder. What is the point for me to beat someone who have the same level as me? it actually works better if you still have a real leaderboard but you just restraint the category to compet against a smaller group of people (by Moodle group instead of course for example - I don't know if it is already supported by block_xp)

I think leaderboards are just not adapted for none competitive people. Maybe the solution is to have an opt-in leaderboard option. None competitive users would not be included or displayed in the leaderboard (but the software still calculates their score if they change their mind). In the case of opt-out we could also make opt-out users invisible Neither they know their ranking, neither the others know their ranking but Moodle does display an anonymous entry with this specific score. Or we just ignore them in the leaderboard.

It is a suggestion :)

**Comment by FMCorz** [comment]
I am not sure how easy it would be to separate students per levels, if there are thousands of students in one course it might be worth it, if there are only a dozen, then I don't see the benefits.

With regards to a leaderboard which only displays your neighbours, how can a student keep track of its progress if the neighbouring students increase and decrease. They would not have a clear idea of who they compete against and their overall rank. Maybe I misunderstood the request.

Thanks!

**Comment by jbourdon** [comment]
Gamers can be broken down into 4 categories. Socializer (75%), explorers (10%), achievers (10%), and killers (5%). Although you can find yourself in multiple categories, this is a general breakdown.  The achievers are interested in being at the top of the leaderboard. In order to make the leaderboard more social, knowing that you need only 20 points to get ahead of the person above you on the board, is motivating. Knowing that you need to get 2000 points to come in first is demotivating and seems unobtainable. 
I am an achiever and by reading your post I would assume you are as well. So being at the top of the board makes sense to us. Right now looking at the leader board in my class (100 students) the top student has more than 3000xp. The majority of students have around 500xp. Will the other student catch up to him, probably not. So the majority of the students aren't trying to come first just simply want to do better than their friends. I would assume the top 10 students on the board are the achievers and are interested in 1st place. 
I guess what I was trying to get across is trying to avoid the demotivation and disengagement experienced by the 80% when the top score becomes unobtainable, or you find yourself at the bottom of the board.

**Comment by mouneyrac** [comment]
Maybe the leaderboard is not a solution for 75% and only people that agree to compet should be exposed to the ladder. We could just disable the leaderboard (if the option exists) and just keep the leveling, then the block is just a motivational tool where you try to reach a new level only know by yourself. No competition :)

**Comment by basethic** [comment]
I think a good decision would be if a user is landed on the page listing his position when he click on the "view the ladder" link. Now the link is showing the first page of the ladder with the users who are at the top of the leaderboard. If we have 1000 users and the user X is listed on the 16th page, he should turn over the pages one by one to find where exactly is he on the ladder. If the landing page is the page with the users position then he is motivated to beat the people ahead.

Cheers,
Dimo

**Comment by FMCorz** [comment]
Just noting here that someone was interested in limiting the ladder to a top 5.

**Comment by jellysmith** [comment]
This has become a very serious problem for us.  Not only do some of our students have hurt feelings about being low on the leaderboard, but some of our top students are using the leaderboard to bully those below them!  Although it is motivating many students, we have to turn the leaderboard off now :-(  

Is there any way to just remove the names from the leaderboard? With an option in the plugin settings, or  in Moodle permissions, or with a change to a line of code? It would be really helpful if students could see their points, and then see the leaderboard to know where they land, but NOT see student names next to the points and levels.  It seems there should be an easy way to do this - any ideas? I don't mind changing code if I know which line to edit! Thanks.

**Comment by FMCorz** [comment]
To be honest the leaderboard was not part of the initial design of the plugin. Experience points are not a metric that it makes sense to compare users with as they represent more student engagements than their abilities.

Have you tried rewarding them individually with hidden activities becoming visible, or with more attractive levels (level 1 is a snail, level 10 is a bear)? Perhaps you can use groups to make other students feel less like they're behind by being in their own ranking.

It saddens me that students are bullying others, but they will always find a way to do so.

I will most likely add a bunch of options for the leaderboard in a later release but in my opinion students should be motivated to level up, not to get more experience points than others.

So far ideas that have come up:

- Limit the leaderboard to neighbours (show 5 before, 5 after)
- Hide neighbour names
- Show the "rank" of the current user without having to check other pages
- Hiding the rank (strange for leaderboard...)

**Comment by FMCorz** [comment]
I am closing this issue. The - soon to be released - version 2.1.0 includes some improvements for the ladder (leaderboard):

* By default the leaderboard opens on the page where the current user is located
* An option was added to hide other participants' name and avatar
* An option was added to limit the ladder to the neighbours of the current user
* An option was added to hide the rank, or display a relative rank

I hope this solves most of the issues that were reported here. If not, please follow up in another issue.

Cheers,
Fred
