### ISSUE TITLE
Erro ao acessar as configurações do plugin

### ISSUE THREAD

**Issue by pabloguto** [FMCorz/moodle-block_xp#123]
Bom dia. Estou realizando testes com o plugin e me deparei com um erro. Ao tentar acessar as configurações de Níveis, regras e visual padrão, além da opção PLUS, surge um erro de programação. Segue abaixo o debug do erro:

Erro de codificação detectado e deve ser corrigido por um programador: Controller for route not found.

Informações de depuração: 
Error code: codingerror

Rastreamento de pilha: 
line 95 of /blocks/xp/local/routing/router.php: coding_exception thrown
line 79 of /blocks/xp/local/routing/router.php: call to block_xp\local\routing\router->get_controller_from_request()
line 38 of /blocks/xp/index.php: call to block_xp\local\routing\router->dispatch()

Já até inseri o diretório CLASSES que seria o caminho correto para o arquivo router.php (blocks/xp/classes/local/routing/router.php mas o erro persiste. Pesquisei e até o momento não encontrei nada sobre este problema.
No aguardo

Server: Debian 10
Nginx
PHP 7.4
Moodle 3.11

**Comment by FMCorz** [comment]
Hi @pabloguto,

Please see this for more details about this error: 
https://levelup.plus/docs/article/error-controller-for-route-not-found

Thank you.

**Comment by pabloguto** [comment]
????



Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Frédéric Massart ***@***.***>
Enviado: terça-feira, 8 de junho de 2021 15:24
Para: FMCorz/moodle-block_xp ***@***.***>
Cc: pabloguto ***@***.***>; Mention ***@***.***>
Assunto: Re: [FMCorz/moodle-block_xp] Erro ao acessar as configurações do plugin (#123)


Closed #123<https://github.com/FMCorz/moodle-block_xp/issues/123>.

**Comment by FMCorz** [comment]
Please see the documentation page:
https://levelup.plus/docs/article/error-controller-for-route-not-found

**Comment by pabloguto** [comment]
OK, desculpe, a outra mensagem havia ido para o spam. Consegui resolver. Muito obrigado


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Frédéric Massart ***@***.***>
Enviado: terça-feira, 8 de junho de 2021 15:46
Para: FMCorz/moodle-block_xp ***@***.***>
Cc: pabloguto ***@***.***>; Mention ***@***.***>
Assunto: Re: [FMCorz/moodle-block_xp] Erro ao acessar as configurações do plugin (#123)


Please see the documentation page:
https://levelup.plus/docs/article/error-controller-for-route-not-found
