### ISSUE TITLE
More granular access control

### ISSUE THREAD

**Issue by t-schroeder** [FMCorz/moodle-block_xp#130]
We would like to disable the "Report" tab for teachers for reasons of data privacy. But to do that we would need to remove the "block/xp:manage" capability. But then teachers couldn't configure the block anymore. So we would like a new capability "block/xp:viewreports".

**Comment by FMCorz** [comment]
Hi @t-schroeder 

Thank you for the suggestion. That's a fair request, we'll do our best to add this to our next release!

**Comment by FMCorz** [comment]
Thank you. This has been included in the latest release `3.12.0`.

**Comment by t-schroeder** [comment]
Hi @FMCorz . Thanks a lot for the quick realization!
