### ISSUE TITLE
Missing students

### ISSUE THREAD

**Issue by phildespres** [FMCorz/moodle-block_xp#136]
Hi,

using latest release and Moodle 3.9.1+ (Build: 20200717), I cannot see all students in the Report tab of the configuration panel at path blocks/xp/index.php/report/1. I see 20 students in the first page and 20 on the second but I have more than that. Normal?

**Comment by FMCorz** [comment]
Hi @phildespres,

When the plugin is used "For the whole site", the report only shows the students that have earned points (or have been observed by the rules in some cases). It does not show all of the users on the system.

What the issue you were describing? If not, the report seems to be behaving correctly for us, we can navigate between all pages.

**Comment by phildespres** [comment]
Ok then, it is a feature and not a bug. I was trying to add points retroactively to students but I guess I will have to do this directly in the DB...

Thanks!

**Comment by FMCorz** [comment]
Thank you @phildespres.

We are aware that the report not showing all students in "For the whole site" mode can be limiting at times. It's neither a bug nor a feature. There are technical challenges to determine which users to display in the report, some Moodle installations would be happy for all users to be in the report, others would not.

We'll re-investigate potential solutions and consider improvements for the next release.

Thanks again!
