### ISSUE TITLE
The YUI module 'moodle-core-formchangechecker' has been deprecated. It has been replaced with 'core_form/changechecker'

### ISSUE THREAD

**Issue by Julian-Tovar** [FMCorz/moodle-block_xp#139]
Good day team. Ever since MDL-69918 has been integrated into Moodle 4.0, the YUI module 'moodle-core-formchangechecker' was deprecated and replaced by 'core_form/changechecker'. You can see that Moodle ticket for examples on how to do the replacement.

The 'block_xp' plugin has one usage of this deprecated YUI module, in `\block_xp_renderer::render_filters_widget_group` which can be found on file 'blocks/xp/renderer.php:694' or here https://github.com/FMCorz/moodle-block_xp/blob/master/renderer.php#L694

**Comment by FMCorz** [comment]
Hi @Julian-Tovar,

Thank you for the heads up. We'll address this soon.
