### ISSUE TITLE
Grade-based award 

### ISSUE THREAD

**Issue by agahe** [FMCorz/moodle-block_xp#142]
Hello,

We use grade-based award in our system. All other rules are disabled. We rely only on a single grade column in the gradebook.
The user achieves successive levels (stars) when he/she receives a corresponding value in one of the gradebook columns ("star number").
The star number column takes natural values in the range [101,105] and 0.
Level 0 corresponds to 0 points
Level 1 corresponds to 101 points
..
Level 5 corresponds to 105 points.

Meanwhile, the Level Up plug-in report contains values outside this range, e.g. 202, 204, 205, 206, 207 ...
For example, a user, in the gradebook in the star number column, has a value of 101  but in the level up report he has a value of 205 and is automatically awarded level 5 instead of 1. How is this possible?

Thank you for help.
Agnes

![gradeitem](https://user-images.githubusercontent.com/10061516/199603730-ca766b58-e36e-4379-977d-7f78a29710a9.jpg)

![stars_level](https://user-images.githubusercontent.com/10061516/199603735-de020db2-8c41-40a2-9e0b-7e44ac8f585c.png)

![raport](https://user-images.githubusercontent.com/10061516/199603737-603eee92-66bd-40e6-862f-978a69e6d7ba.png)

![gradebook](https://user-images.githubusercontent.com/10061516/199603740-e1ccca02-bee8-4445-84c8-bdffb82a3acf.png)

**Comment by FMCorz** [comment]
Hi @agahe,

I am unsure why this is happening. The only reason why XP would aware more points than the grades is if they received points for another rule, or a drop. Could you please check the logs of those particular learners?

Would you please email us directly at this address: support @ levelup . plus ?
