### ISSUE TITLE
PHP Notice when updating 

### ISSUE THREAD

**Issue by aojusto** [FMCorz/moodle-block_xp#147]
Hi all,
I am getting the following when upgrading block_xp from v3.12.1 to v.3.13.0 into our Moodle 3.11.11:

PHP Notice: The renderer was requested too early in the process.* line 383 of /local/xp/classes/local/container.php: call to debugging()
* line 105 of /local/xp/classes/local/container.php: call to local_xp\local\container->get_renderer()
* line 54 of /blocks/xp/classes/di.php: call to local_xp\local\container->get()
* line 78 of /blocks/xp/classes/local/setting/recommended_plugins_setting.php: call to block_xp\di::get()
* line 151 of /blocks/xp/classes/local/setting/default_settings_maker.php: call to block_xp\local\setting\recommended_plugins_setting->__construct()
* line 84 of /local/xp/classes/local/setting/settings_maker.php: call to block_xp\local\setting\default_settings_maker->get_general_settings()
* line 98 of /blocks/xp/classes/local/setting/default_settings_maker.php: call to local_xp\local\setting\settings_maker->get_general_settings()
* line 74 of /local/xp/classes/local/setting/settings_maker.php: call to block_xp\local\setting\default_settings_maker->get_settings()
* line 36 of /blocks/xp/settings.php: ca in /var/www/releases/uvigo-vle-moodle/uvigo-vle-moodle-20221201-145308/web/lib/weblib.php on line 3268

Thanks in advance.

**Comment by FMCorz** [comment]
Hi @aojusto,

Thank you for your comment. I believe you had commented about this issue on moodle.org. We could not replicate it locally but have attempted to solve it in v3.13.1. As I mentioned to you this message is inoffensive, but please do let us know if this is still an issue upgrading to 3.13.1.

Kind regards,
Fred

**Comment by FMCorz** [comment]
I should mention that we released v3.13.1 two days ago:
https://docs.levelup.plus/xp/release-notes
