### ISSUE TITLE
Default language strings

### ISSUE THREAD

**Issue by sollericos** [FMCorz/moodle-block_xp#148]
Hi. When adding a new XP block, the title and description fields default to English. Can be filled with the strings in the default language configured in the site?

At AMOS these strings are: Levelup and participatetolevelup

Thanks.

**Comment by FMCorz** [comment]
Hi @sollericos,

Thank you for reporting this!

Both languages strings are used to define what the default title and description should be, in the admin settings. I suspect that your installation of XP was done in English, and thus default values were set in English. If the title and description were not customisable we would most certainly use the language strings directly, but as those are set in the admin, we cannot.

To update the title and description, navigate to Site admin > Plugins > Blocks > Level Up XP > Default settings.

Note that changing the default settings will not propagate to courses where the block had previously been added.

Please let me know if any of the above does not appear correct.

Kind regards,
Fred

**Comment by sollericos** [comment]
Thanks Fred! This solves my question. I didn't see the default settings screen.
