### ISSUE TITLE
Cron job fails in manager.php at "continue;" in if-statement

### ISSUE THREAD

**Issue by danawortman** [FMCorz/moodle-block_xp#15]
This has happened in several versions of the moodle XP block and I have simply fixed it manually each time, but that is becoming annoying with every update.

I am running PHP v 5.4.36 on a Linux machine and in manager.php, the following line causes the following fatal error:

Processing cron function for xp....PHP Fatal error:  Cannot break/continue 1 level in /var/www/html/moodle/blocks/xp/classes/manager.php on line 452

In manager.php:

    /**
     * Purge the logs according to preferences.
     *
     * @return void
     */
    public function purge_log() {
        global $DB;
        $keeplogs = $this->get_config('keeplogs');
        if (!$keeplogs) {
            continue;
        } else {
            // The cron is set to run only once a day, so no need to test the last time it was purged here.
            $DB->delete_records_select('block_xp_log', 'time < :time', array(
                'time' => time() - ($keeplogs * DAYSECS)
            ));
        }
    }

Continues can only be used in looping constructs as they mean "jump to the next iteration" - if statements do not have multiple iterations.  As there is no loop in this function, the continue is irrelevant.  A default installation of PHP will fail on this line (I'm not even sure how you're getting this to run yourself!).

In this case, since the line means nothing and does nothing, I simply comment it out without impacting the functionality of the code.

HOWEVER - this causes the CRON job to fail for the ENTIRE moodle site, which is where this becomes a serious issue.

Please fix this issue in your next push.

**Comment by FMCorz** [comment]
Thanks for reporting this bug.

I know what the continue statement is for, and I must have left it there by mistake. During development it is pretty difficult to test all the written bits and pieces of code, even for a small Moodle block, I must not have disabled logging and run cron at the same time.

For the future, may I suggest you report the bug as you find it, and provide a solution or a workaround for the other users that might face the same issue? Keeping on patching the block for several releases was indeed not the best choice. This is Open Source after all, sharing the problem and the solution earlier would have benefit everyone.

Thanks,
Fred
