### ISSUE TITLE
Usage report cron throws error "Class not found"

### ISSUE THREAD

**Issue by arvvns** [FMCorz/moodle-block_xp#151]
plugin version: 2022112609

Execute scheduled task: Usage report (block_xp\task\usage_report)
... started 13:46:05. Current memory use 2.5 megabaitai.
Debugging increased temporarily due to faildelay of 15360
... used 0 dbqueries
... used 0.23039293289185 seconds
Scheduled task failed: Usage report (block_xp\task\usage_report),Class 'local_xp\local\plugin\addon' not found
Backtrace:
* line 74 of /blocks/xp/classes/local/plugin/usage_reporter.php: call to block_xp\local\plugin\usage_report_maker->make()
* line 64 of /blocks/xp/classes/task/usage_report.php: call to block_xp\local\plugin\usage_reporter->report()
* line 259 of /lib/cronlib.php: call to block_xp\task\usage_report->execute()
* line 167 of /admin/cli/scheduled_task.php: call to cron_run_inner_scheduled_task()

**Comment by FMCorz** [comment]
Hi @arvvns, thank you for reporting this! We've addressed the issue and tagged a new version 3.13.3, we will release it shortly on Moodle.org.
