### ISSUE TITLE
PHP 8.0 Compatibility Issue - Required parameter follows optional parameter in __construct()

### ISSUE THREAD

**Issue by michael-milette** [FMCorz/moodle-block_xp#153]
PHP Deprecated:  Required parameter $userid follows optional parameter $options in blocks/xp/classes/output/leaderboard_table.php on line 82

In PHP 8.0, you can no longer have required parameters appear after optional parameters:

For more information, see [PHP 8.0: Deprecate required parameters after optional parameters in function/method signatures](https://php.watch/versions/8.0/deprecate-required-param-after-optional)

**Comment by FMCorz** [comment]
Hi @michael-milette,

Thank you for reporting this, this was most definitely not intentional. It has been fixed and will be included in our next release.

**Comment by michael-milette** [comment]
Hi @FMCorz , thank you very much for the quick fix! I never thought that it was intentional. Your quick response is so very much appreciated.

Best regards,

Michael
