### ISSUE TITLE
Problem with Level Up XP+ message

### ISSUE THREAD

**Issue by TheBryanOpen228** [FMCorz/moodle-block_xp#158]
We are using Moodle version 4.1.3 (Build: 20230424) 
block_xp version 3.14.0 (2023042400)
local_xp version 2022112610
Broken Behat test: [blocks/xp/tests/behat/teacher_explore.feature](https://github.com/FMCorz/moodle-block_xp/blob/v3.14.0/tests/behat/teacher_explore.feature#L36)

When executing the Behat test presented, i got the following error:`No 'Discover Level Up XP+' text Found on page`
This is probably because we recently installed the Level Up XP+ plugin (local_xp), which causes it to never display the corresponding text to offer the installation, see [blocks/xp/classes/local/controller/promo_controller.php:170](https://github.com/FMCorz/moodle-block_xp/blob/v3.14.0/classes/local/controller/promo_controller.php#L170) and [blocks/xp/classes/local/controller/promo_controller.php:146](https://github.com/FMCorz/moodle-block_xp/blob/v3.14.0/classes/local/controller/promo_controller.php#L146).  At the moment the fix I made was only to change the text to search for, leaving the behat step as `Then I should see "Level Up XP+"`
This way the test is still functional and is not limited to the case where the Level Up XP+ plugin is not installed.

**Comment by FMCorz** [comment]
@TheBryanOpen228, I believe we addressed this in v3.14.1 (just released). Please let us know if the issue persists.
