### ISSUE TITLE
Moodle Mobile App - Block is Not Visible 

### ISSUE THREAD

**Issue by EdTechSuccess** [FMCorz/moodle-block_xp#159]
The Block is not visible in the Moodle Mobile app (v4.1+). Will you be making the block compatible with the mobile app?

**Comment by FMCorz** [comment]
Hi @EdTechSuccess, are you using our XP+ package? The latter includes mobile support for levels, progress and leaderboards.

**Comment by EdTechSuccess** [comment]
Hi @FMCorz, no I am using the free package. To have mobile functionality, I would need to upgrade to XP+?
