### ISSUE TITLE
Deprecation warnings with PHP 8.2

### ISSUE THREAD

**Issue by thepurpleblob** [FMCorz/moodle-block_xp#161]
Moodle 4.3 and PHP 8.2. Lots and lot of (just an example)...

Deprecated: Creation of dynamic property block_xp\local\routing\route_definition::$name is deprecated in /app/public/blocks/xp/classes/local/routing/route_definition.php on line 48

Deprecated: Creation of dynamic property block_xp\local\routing\route_definition::$url is deprecated in /app/public/blocks/xp/classes/local/routing/route_definition.php on line 49

Deprecated: Creation of dynamic property block_xp\local\routing\route_definition::$regex is deprecated in /app/public/blocks/xp/classes/local/routing/route_definition.php on line 50

Deprecated: Creation of dynamic property block_xp\local\routing\route_definition::$mapping is deprecated in /app/public/blocks/xp/classes/local/routing/route_definition.php on line 51

Deprecated: Creation of dynamic property block_xp\local\routing\route_definition::$controllername is deprecated in /app/public/blocks/xp/classes/local/routing/route_definition.php on line 52

Underlying issue looks like https://php.watch/versions/8.2/dynamic-properties-deprecated

As the latest version supports Moodle 4.3 and 4.3 supports PHP 8.2, it would be great if this could be fixed.

**Comment by FMCorz** [comment]
Thanks @thepurpleblob. Odd that this was not been raised during our testing. We will address it soon. Thank you!
