### ISSUE TITLE
function user_preference_allow_ajax_update deprecation

### ISSUE THREAD

**Issue by fvargas-olms** [FMCorz/moodle-block_xp#165]
Hi there,

With the changes made in [MDL-76974](https://tracker.moodle.org/browse/MDL-76974) Moodle deprecated function `user_preference_allow_ajax_update`. I create this issue to report that you have a reference to this deprecated function [in this line](https://github.com/FMCorz/moodle-block_xp/blob/947704522efe979c9fece54796edc06c56d62622/renderer.php#L333C17-L333C50).
Could you take a look at this deprecation to remove it? Thanks!

**Comment by FMCorz** [comment]
Hi @fvargas-olms,

Thank you for reporting this. Has there been any debugging message or error that prompted you to report this? As you can see from [this line](https://github.com/FMCorz/moodle-block_xp/blob/947704522efe979c9fece54796edc06c56d62622/renderer.php#L317) this function is no longer used from Moodle 4.3. We only kept it for backwards compatibility.

**Comment by FMCorz** [comment]
Closing as this does not appear to be a bug. Please provide replication steps if I am mistaken.
