### ISSUE TITLE
Level Up Course Report Error

### ISSUE THREAD

**Issue by wings2fly2** [FMCorz/moodle-block_xp#18]
Hello, 

I recently uploaded the Level Up plugin and am excited to start using it. 

When looking through the settings for the Level Up block, I see an error under that "Course Report" tab. No other errors occurred within the other tabs, so I am curious if this is a normal occurrence. The error was "Coding error detected, it must be fixed by a programmer: moodle_database::get_in_or_equal() does not accept empty arrays" and then asks me to visit https://docs.moodle.org/28/en/error/debug/codingerror  -I should note that currently there are no students enrolled as I am working with a copy of the site. Is this how it is supposed to operate before students are enrolled?

*I would also like to request a filter per specific assignment if that is possible.

Thank you!

**Comment by FMCorz** [comment]
Thanks. I will fix it. Regarding the filter, #11 seems to already be about that.

**Comment by wings2fly2** [comment]
Thank you, Fred. I'm looking forward to #18 being supported, too.

Please let me know if there is anything I need to do to the system after it
is fixed. Thank you.

*Kirsten L. Stein**, Ed.D.*
Athena's Advanced Academy
Founder and Instructor
Kirsten@AthenasAcademy.com
AthenasAcademy.com
