### ISSUE TITLE
notification of level up

### ISSUE THREAD

**Issue by mouneyrac** [FMCorz/moodle-block_xp#2]
it works great fred. 

My feedback as a user:
* as a student I'm not notified that I gained a level. I should be congratulated by a temporary "on-screen" message like the one saying that you can drag&drop file. I'm expecting like a fireworks and special effect because I leveled up :)
* as a student (and as a teacher) I have no clues on what to do to level up. What is the stuff I need to do to level fast? Where is it written?
* what is the maximum level? Usually there is a maximum level, it's more motivating. I guess "subject master" student always end up to leave a course at a moment or at another. A maximum level could be just a tricky way to keep them a bit longer than the expected average presence of a "subject master".

Anyway it works great, I'm level 2 :P

**Comment by mudrd8mz** [comment]
I think all these are fixed by now.

* There is now a nice pop-up when a student levels up.
* The instructions can be stated clearly by the teacher in the block configuration.
* The maximum level, should the students be aware of it, is available at the Infos page.

**Comment by FMCorz** [comment]
Thanks, closing.
