### ISSUE TITLE
bug : visuals

### ISSUE THREAD

**Issue by maximedub** [FMCorz/moodle-block_xp#24]
I just update my moodle with the last version of the plugin (2.0.0). It's really a nice work. But I can see that personnal level badges don't work.
So I try on localhost plateforme. and it's the same thing : moodle tell me that the link to the picture is broken.
when I try to see the link of the badge number 2, I have URL like this : http://www.mywebsite.com/moodlesite/pluginfile.php/1/block_xp/badges/0/2

**Comment by FMCorz** [comment]
Hi,

The bug is caused when the new setting to gather XP for the whole site is enabled. Adding that feature was likely to have a few bugs, it is now fixed in the master branch. I will release a version 2.0.1 tonight.

Thanks for the quick feedback!
Fred
