### ISSUE TITLE
Reward a student for a grade received

### ISSUE THREAD

**Issue by FMCorz** [FMCorz/moodle-block_xp#25]
A new rule could be added to observe the grades the students receive.

**Comment by Kathrin84** [comment]
Hi, 

this is what I would also like to have.

Unfortunately, at the moment, I'm not quite sure how to use your plugin or what events are covered. Events, like a student submitted a solution is not so good to gain XP. It's better to ckeck if they were graded or even better if they passed the task.

I looked through the events list and the only event I found was: mod_assign\event\submission_graded.
So I tried to create an own rule:
![own_event](https://cloud.githubusercontent.com/assets/4711883/10992175/c47770ca-8463-11e5-8f46-a171fe068224.png)

However, it's not working.

Could you explain me, what is wrong or if not all of the events of the events list could be used, which of them can be taken? I didn't find any differences to events that work e.g. core\event\course\viewed.

Cheers,
Kathrin

**Comment by FMCorz** [comment]
Hi Kathrin,

I don't know why this wouldn't work, it should. Could you check the "log" and see if that events is logged at all? The way you appeared to have set this up would give 200 points to any students who have their assignment submission graded.

Cheers,
Fred

**Comment by Kathrin84** [comment]
Hi Fred,
ah, now I understand. ;) What educational levels do you cover? Only Participating or more?
When you say, it takes quite a bit of work to fix that, do you plan to integrate events from more educational levels or how do you want to fix it?
Cheers,
Kathrin

**Comment by FMCorz** [comment]
I only cover "Participating" events because they are the ones which are most likely associated with an action that a student would be taking in a course. The plugin was initially developed to magically reward students with XP as they were doing things. It then became more complex but I did not think at the start that teaching actions could impact users. I think the best way for me to fix this is simply to create specific rules which relax the 'educational level' filtering to accept teaching because I cannot simply accept all teaching events. (they are not linked to users the same way)

Actually, when you think about it, I am not sure how rewarding it is when a teacher grades an assignment and they obtain 200 XP because it is not "live". Assuming they also gain XP when doing other things, they might not even realise that X or Y assignment gave them points.

It has been a while that I have been thinking of implementing quests and achievements. For instance, a quest would sort of encourage student to browse the content, e.g. "Find what O² means", but maybe it could be "Obtain a grade of at least n for the assignment about O²". Especially when role-played pretending that a NPC (non playable character) is grading the assignment. Then when the quest is complete they could be rewarded with XP. Achievements are probably very similar, but still a bit different. I guess it whole depends on how quests and achievements they are phrased.

My point is that if we have quests, then gaining XP for a grade received makes more sense as it's a delayed reward. Though quests do not always have to be delayed rewards. I'd make quests another plugin but hook it with block_xp.

Anyway, this is very interesting and I'll keep thinking about.

Please do not hesitate to share what you are trying to do.

Cheers,
Fred

**Comment by Kathrin84** [comment]
Hi Fred, 
thanks a lot for your further explanation. Now, I think I understand what you originally intended with this block. I personally understood it the quest like way. This might be due to my MMORPG experience. ;)

I think, as you also mentioned, that are two ways. One is to encourage users to be more active in the course itself. The other way is to reward users with XP for completing a task or quest. In our environment, the second one is more attractive and it would be great if you would invest more time for implementing such a feature. I really love the idea of creating quests out of the rules and then gain XP for completing them. :)

Cheers,
Kathrin

**Comment by mvit777** [comment]
Upvote for "rewarding points upon completion of  a quiz or a scorm"!
Also available for extensive testing in case you are thinking of implementing it

Cheers,
M.

**Comment by Andrewolico** [comment]
Great plugin.

I'd like to add support for "rewarding points upon completion of a quiz or a scorm" too.

And also to have a group leader board option rather than names of individuals.

Is there anything we can do to help make this happen?

Thanks
Andrew

**Comment by FMCorz** [comment]
Thanks @Andrewolico, could you raise a separate issue for the group leader board? Thanks!

**Comment by cborn** [comment]
I'd like to support the idea of being able to award XP to students when they reach a certain (passing) grade on activities, or an activity is marked complete when graded. Gamification research suggests that awarding points based on the performance of the student (how well they do on assignments) supports their feeling of agency in the work they are doing.  Therefore, they have control over how well they can do, essentially providing more motivation to do better on assignments.

**Comment by FMCorz** [comment]
Well, good news, that's something that I'm working on ;-).

**Comment by kimchilds** [comment]
Hi there,

Is there any update on the ability to reward students xp based on their grade?

Thanks

**Comment by FMCorz** [comment]
Hi @kimchilds, 

Yes, this feature is available with out [Level up! Plus](https://levelup.plus) addon.

More information on how it works here: https://levelup.plus/docs/article/grade-based-rewards

**Comment by kimchilds** [comment]
Hi there,

Thanks for the prompt reply. I have looked into the rulesets around rewarding xp based on grades. 

Referring to the example in the documentation, "Alice submits an assignment, and receives the mark of 40/100. In Level up!, Alice receives 40 points for her grade. Alice then reattempts her assignment, but this time her grade is lowered to 25/100. Alice's points in Level up! do not change. For her final attempt, Alice scores 60/100, she earns 20 additional points, her total of points earned is 60".

What if a user gets 100/100 on the first attempt. They will receive 100 points. But what does this mean when want to complete it a second time if there is unlimited attempts for a quiz. Will they not receive any more points?

Thanks,

**Comment by FMCorz** [comment]
A student will never get more points than the maximum grade, once they get the maximum grade they won't get a chance to earn more points for the given grade item. If you're looking at rewarding taking the quiz more than once, you could observe some of the quiz events, although in that case they would get the points regardless of their performance.
