### ISSUE TITLE
XP gain disables automatically after sometime

### ISSUE THREAD

**Issue by mikeross6233m** [FMCorz/moodle-block_xp#31]
I am having some problem with a block_xp plugin.

Sometimes the block_xp shows "XP gain disable" and when I enable it after some time I notice the same thing.

**Comment by mikeross6233m** [comment]
I noticed that whenever I restart my computer the xp gain disables.

**Comment by mikeross6233m** [comment]
It is still happening every time..
Any suggestions??

**Comment by FMCorz** [comment]
I can't reproduce this bug, did you find a solution or is it still happening?

**Comment by FMCorz** [comment]
I'm closing this, please reopen a new issue if the problem remains.
