### ISSUE TITLE
No comments possibles

### ISSUE THREAD

**Issue by Mautefort** [FMCorz/moodle-block_xp#32]
Hello,

I would like to know if it would be possible to create a new fonction for writing coments. I mean by this: being able to write a comment on the pop-up when the student gains a new level. It would give more pedagogical value to the plug-in.

Thank you

Marie

**Comment by FMCorz** [comment]
Thanks, it makes sense.

**Comment by FMCorz** [comment]
I've developed a quick and easy solution for this, which can be found in this commit: b15cc49e82c7056077de1309f07fcd37d246f790 but I don't like it so I'm not releasing it yet.

Mainly, there are performance issues (eventsdata JSON growing), and no way to preview the notification dialogue. I'll think a bit more how to improve this further.

**Comment by FMCorz** [comment]
Closing as this has been addressed in the form of giving a name and description to a level, and customising the level up notification message in [XP+ 1.15](https://docs.levelup.plus/xp/release-notes#xpp-1-15-0).
