### ISSUE TITLE
Custom image

### ISSUE THREAD

**Issue by Mautefort** [FMCorz/moodle-block_xp#33]

**Comment by FMCorz** [comment]
Hi,

> I created different icons for the different courses of my Moodle but I reallyze now that only one type of custom image is displayed. There is no way to have a different set of image per course?

Is this still an issue? I can't seem to be able to reproduce it.

**Comment by Mautefort** [comment]
No, it's not, I'm sorry. I found the solution in the course parameters.

2016-02-16 5:18 GMT-02:00 Frédéric Massart <notifications@github.com>:

> Hi,
>
> I created different icons for the different courses of my Moodle but I
> reallyze now that only one type of custom image is displayed. There is no
> way to have a different set of image per course?
>
> Is this still an issue? I can't seem to be able to reproduce it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FMCorz/moodle-block_xp/issues/33#issuecomment-184556365>
> .
>



-- 

*Marie Autefort | Equipe pedagógica - E-learning*


*IFESP Formação - E-learning - Intercâmbio*
Av. Brig. Faria Lima, 1826 - 7° andar - Cj. 703 - São Paulo
Tel: (5511) 3031-3599 / 2308-7837
pro1@ifesp.com.br <pro7@ifesp.com.br>

*Conheça nossos sites:*


   - *IFESP <http://www.ifesp.com.br/>*
   - Curso de Francês online <http://www.cursodefrancesonline.com.br/>
   - *Universidades Francesas <http://www.universidadesfrancesas.com.br/>*
   - *O Melhor de Paris <http://www.omelhordeparis.com.br/>*
   - My Little Brasil <http://www.mylittlebrasil.com.br/> (em francês)
   - Portugais en ligne <http://www.portugaisenligne.com/>

*Siga o IFESP nas redes sociais:*

<https://www.facebook.com/ifesp> <https://twitter.com/ifesp>
<http://www.linkedin.com/groups/IFESP-Franc%C3%AAs-Intensivo-Online-Objetivo-3903368?gid=3903368&mostPopular=&trk=tyah>
<http://www.slideshare.net/ifesp> <http://www.youtube.com/user/ifesp>

**Comment by FMCorz** [comment]
No worries.
