### ISSUE TITLE
Setting Level Up! block as default block inside course

### ISSUE THREAD

**Issue by zienil** [FMCorz/moodle-block_xp#34]
Hello.. right now im using Level Up! plugin inside Moodle 3. The problem is i have more that 800 courses and I need to add manualy one-by-one Level Up! block inside each and every courses. Is there any easy way to setting the Level Up! block as default block inside course? Thanks you.

**Comment by FMCorz** [comment]
I believe this is two issues in one:

* The lack of such an option in Moodle itself.
* #26 in which I should add defaults

I suggest you ask on Moodle.org forums how to populate many courses with a block. A little script to apply the config you want to each block_xp instance shouldn't be a problem.

Thanks!

**Comment by zienil** [comment]
orite.. thanks for the respond. :D
