### ISSUE TITLE
Ladder page not accessible on php 5.4.31

### ISSUE THREAD

**Issue by polder** [FMCorz/moodle-block_xp#36]
XP block version: 2016022404  -> '2.1.1'
Moodle 3.0.2+ (Build: 20160225)
PHP 5.4.31 (minimum version required by moodle 3.0.2+ is 5.4.4)

Fatal error: Can't use method return value in write context in [......]\blocks\xp\ladder.php on line 62

In php <5.5 empty() only checks variables as anything else will result in a parse error. In other words, the following will not work: empty(trim($name)).

**Comment by FMCorz** [comment]
Whoops. Thank you. Will fix this ASAP.

**Comment by nezmo1** [comment]
Ole, 
I am lil programmer but I have soloution for this!

![screenshot_2](https://cloud.githubusercontent.com/assets/6652331/13997810/238ccad2-f134-11e5-81b7-3a4adac4e69a.jpg)
