### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by Mautefort** [FMCorz/moodle-block_xp#40]
Hello,

I have a problem since a few days with the plug-in pages (ranking, information, report, configuration). When I click, I land in the page with this message : 
_Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at webmaster@cursodefrancesonline.com.br to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.
Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request._

It's the first time this problem happens. The Moodle version is 2.9 and the plug-in version is 2016032700.

Do you have any idear what's going on ? 

Thank you

**Comment by FMCorz** [comment]
Sorry but I will need more information to address this. As this issue is quite old, I'll close it for now, feel free to add more to it if this still is a problem to you.
