### ISSUE TITLE
Block Links Not Working - Not Found

### ISSUE THREAD

**Issue by leeheeman** [FMCorz/moodle-block_xp#41]
Ok, so in the level up block you have Information, View Ladder, Report, and Settings. Clicking any of these takes me to the following URL: http://www.domain.come/blocks/xp/config.php?courseid=29

However, this returns a Not Found page. This does not work at all and I don't know why. I'd really like this plugin to work.

**Comment by FMCorz** [comment]
Hi, thanks for the report. Could you perhaps see with your administrator if something conflicts and redirects you elsewhere? This is the first time I'm hearing about this.

**Comment by leeheeman** [comment]
I will say that my Moodle installation isn't the root folder. It's one folder up from our Wordpress installation on our domain.

That being said, our Wordpress installation hasn't previously caused any issues and I don't see how it would affect this part of Moodle.

**Comment by leeheeman** [comment]
Ok, it's been 11 days and no responses. I checked my redirects, and there are none that would affect it. In fact, I disabled all of my redirects to test it out. I still have the same problem. Page not found.

**Comment by FMCorz** [comment]
What version of Moodle are you using?

**Comment by leeheeman** [comment]
Ok nevermind about all this. I tried uninstalling and reinstalling. That seemed to do the trick. There must've been an interruption in the first installation.
