### ISSUE TITLE
Leader board for groups

### ISSUE THREAD

**Issue by Andrewolico** [FMCorz/moodle-block_xp#42]
Hi Frédéric,

Thank you for a great plugin. 

One addition that we'd be really keen to use would be to have an option of a leader board for groups similar to the one currently for individuals. We think there's some really nice opportunities to promote collaborative work amongst a group learners that is reflected in a group score.

Thanks for the consideration. Happy to help where possible.

Andrew

**Comment by FMCorz** [comment]
Thanks for suggesting this, it's a good idea.

**Comment by FMCorz** [comment]
This has been implemented in _Level up! Plus_ a couple of months ago. Teams can be created based on course groups, or cohorts. Thank you for the suggestion. Closing.
