### ISSUE TITLE
Ability to reward a student for results instead of just participation

### ISSUE THREAD

**Issue by fproctor** [FMCorz/moodle-block_xp#44]
Hi all,

I am a site administrator running version 3.1.2 hosted on GoDaddy. I have a requirement for the site to track students progress through our online educational curriculum that teaches sales techniques. Completing each course can have a grade ranging from 2.0 to 4.0. _We want the completion of any course to satisfy awarding of completion point(s) that are fixed regardless of the final course grade as long as that grade met a minimum standard of passing the course._ We would want Students, Teachers, and Managers to be able to view current status, generate reports, and have the point value for completed courses indicated on each course completion certificate (I am still learning how to use the certificate plugin). In the US, we typically use Quarter or Semester hours with credits ranging from 1 to 5 per course completion depending on complexity and/or duration of the class. 

I was going to implement the badge system to track this but it just doesn't quite meet my intent. The downside is each proficiency level would be tied to completing a fixed set of specific courses instead of a number of random courses. For our site, each student would be free to browse all available course and self-enroll. 

I've installed the "Level Up!" plugin/block and we're still configuring it. We like the interface and it almost meets our goals. An example course would be to watch one video then take one quiz based on that video content. We are finding that within the rule structure of "Level Up!", we can specify a conditional rule where a quiz that is simply submitted would satisfy the rule. In this scenario, even if the student failed the quiz (and, thus, the course), the rule was met and credit given. I'm looking for a bean count (each course completed) where each bean can have a value I specify. Then be able to link those values to a ranking (that part appears to be in place), manipulate those values individually or as a total in an output report, on a course completion certificate, and/or on a curriculum completion certificate. 

Each student would fit into a proficiency hierarchy:

**Ranking        Credit Range**
Freshman         0-29
Sophomore   30-59
Junior       60-89
Senior       90+

The semantics of proficiency ranking may change to something along the lines of "Beginner, Intermediate, Advanced, Expert" but requirement of tracking the credit per completed course would not change. 

Regards,
Fred Proctor

---

This is in regard to the following extract from the [Moodle Forum] addressing Level Up! functionality (https://moodle.org/mod/forum/discuss.php?d=331329). 

> The plugin was designed to reward a student for their participation, not for their results. Somehow I added a leaderboard but, just like in an RPG, ranking players by their level is not a good metric as it's only reflects on how much time they have invested in the game/course.
> 1. Can this plugin be used for ranking participants based on activity completion i.e points to be added only when an activity gets completed?
> 
> No, for the reasons mentioned above.
> 1. points to be added only when a participant clears an assessment with a specific grade
> 
> No, for the reasons mentioned above.
> 1. points to be added only if a participants gets a certain grade for an assignment submitted
> 
> No, for the reasons mentioned above.

**Comment by FMCorz** [comment]
Just mentioning that rewards based on activity completion, with or without a required grade, are both supported through the add-on [Level up! Plus](https://github.com/FMCorz/moodle-local_xp).

For points solely based on a grade received, this is not yet available. I'm closing this issue and will keep #25 as the grade one.
