### ISSUE TITLE
Upload exp from file

### ISSUE THREAD

**Issue by Shaomk** [FMCorz/moodle-block_xp#45]
Hi!
Thank you for a great plugin.
One addition that:
For the rating table from another database. 
1) I turn of gain experience. 
2) I want to upload the experience of the table (the user / experience).

It would be great!

Thanks for the consideration

**Comment by FMCorz** [comment]
I guess we could have an import/export feature of the XP of each student. Thanks for the suggestion.

**Comment by FMCorz** [comment]
This was added to Level up! Plus (Pro & Multi) under the _Import by CSV_ feature available in the report page.
