### ISSUE TITLE
integrate with moodle grading

### ISSUE THREAD

**Issue by Canx** [FMCorz/moodle-block_xp#48]
Hi Frederic,

this is not an issue, it's more of a feature request or desire:

it would be great to have a qualification item associated with moodle grading system where automatically it would grade a student based on its current level or points achieved.

Now I do a manual correspondence between points/level and grade, like this:

level >28 -> 10
level 25-27 -> 9
level 20-24 -> 8
....

NOTE: In Spain we grade from 0 to 10

I would love to define a table somewhere and let Moodle grade my students by me :)

I don't know if this would require another project, maybe a new activity module? What do you think?

**Comment by FMCorz** [comment]
Hi Canx,

I believe that this would work better as separate plugin. Not necessarily an activity module, but a plugin which would be a bridge between "Level up" and the Gradebook. This definitely requires custom development.

Cheers,
Fred
