### ISSUE TITLE
Reset experience points

### ISSUE THREAD

**Issue by Canx** [FMCorz/moodle-block_xp#49]
Hi, this is related with #47.

As recalculating points seems difficult to implement a workaround for me would be to reset experience points for all students at any given point in time, and then change the current rules. Haven't found any reset button so I suposse I'll have to dig in the database...

I don't want to pressure you Fred, but Christmas is coming ;)

Regards,
Ruben.

**Comment by FMCorz** [comment]
You can already reset the course. See at the bottom of the report.

**Comment by Canx** [comment]
I may be getting blind, thank you!

**Comment by FMCorz** [comment]
No worries, closing.
