### ISSUE TITLE
event rule for a task/activity that has a pass grade

### ISSUE THREAD

**Issue by rcancho** [FMCorz/moodle-block_xp#51]
Hi Fred,

the list of events in rule creation is very big but I miss this rule: earn points only when you submit an activity that has a pass grade. 
So maybe you could earn some points when you submit the task but you earn the bulk points when the task achieves a passing grade.

Reading the code I don't know if that should be done in the external plugin that provides its own events or here...

**Comment by FMCorz** [comment]
Hi,

At this stage there is no way to achieve this without custom development. The plugin only looks at the event, not what they are related to. For instance, if you submit an assignment you will get experience points, regardless of the settings of the assignment, or the eventual grade you will be given.

**Comment by FMCorz** [comment]
See #44.

**Comment by FMCorz** [comment]
Just commenting that can be solved using the add-on [Level up! Plus](https://github.com/FMCorz/moodle-local_xp), combined with activity completion set to requiring a passing grade.

**Comment by FMCorz** [comment]
Closing.
