### ISSUE TITLE
New student orientation and Level Up

### ISSUE THREAD

**Issue by StaceyEK** [FMCorz/moodle-block_xp#53]
Hi, I'm creating a new student orientation for a university, and Level Up is a great candidate for motivating/rewarding students for achieving orientation goals. Here is the problem. While participation points are fine, students need to understand what constitutes participation and at the moment it seems a bit opaque. When our students test the orientation they don't understand why they are getting points. I would prefer to just reward "activity completion"  in Moodle. Is there a way to zero out the activities tracking? 

Thanks for considering this

**Comment by FMCorz** [comment]
Thank you for the report, and sorry for having never commented! _Level up! Plus_ includes rewards for completing activities or courses. Additionally, the block can display the list of recent rewards and the information page can be used to explain to students how they can earn points and level up. Closing as I believe this is no longer an issue.
