### ISSUE TITLE
logs filtered by user

### ISSUE THREAD

**Issue by Canx** [FMCorz/moodle-block_xp#60]
My students complain why they don't get their points if they do their job. I would like an easy way to justify them the points they get, or even better, let them see their log points events.

An option would be to have a filter in the log tab by user in the teacher log tab.
Other option would be to have a report link in the user view that pointed to the log tab, filtered by the current user.

**Comment by FMCorz** [comment]
Closing, this has been added in [XP 3.13](https://docs.levelup.plus/xp/release-notes#xp-3-13-0).
