### ISSUE TITLE
Rules page not working when plugin set for the whole site

### ISSUE THREAD

**Issue by cardetdev** [FMCorz/moodle-block_xp#61]
Hi, I tried to setup the plugin on the course level and the rules work fine, but when I set it for the whole site it gives a blank page with the following error: 
 Fatal error: Call to undefined function course_get_format() in [MYMOODLEPATH]\blocks\xp\classes\rule_cm.php on line 89
I tried uninstalling and installing to remove all db entries on course-relevant rules but the issue still remains. 

Using the latest version of the plugin and Moodle 3.2.2

**Comment by FMCorz** [comment]
Whoops. Well spotted!

I'm guessing a good workaround  was to:

* Revert to "One per course"
* Remove the rules attached to specific activities
* Change to "For the whole site" again

**Comment by Canx** [comment]
I'm ignorant so I'll ask: why would you want to have a site "level up" block? In which context would be interesting check progress outside courses?

**Comment by FMCorz** [comment]
That request came from other people who do not "track progress", it's more rewarding for what you're doing. So, rather than the teacher using the block, you can see that as the platform offering some sort of XP level, just like some other MOOCs.

**Comment by FMCorz** [comment]
My analysis was incorrect. The file containing `course_get_format` is not loaded when debugging is turned off. I'm not sure how many are affected by this, whether it's new or not, but the patch should fix it.
