### ISSUE TITLE
custom badges display correctly for teacher, but not students

### ISSUE THREAD

**Issue by alymanbuttler** [FMCorz/moodle-block_xp#64]
This bug is similar to #24 

Things I have tried to fix it:
1) change permissions on image files to 755
2) switch to "whole site" and then back to "in courses"
3) deleting the images and then uploading them again

I love the plugin--thanks so much for making & supporting it.

**Comment by FMCorz** [comment]
Thanks, I will investigate.

**Comment by FMCorz** [comment]
I've tried to reproduce this, bug cannot. It works as expected, both teachers and students can see the custom badges. Note that in order to use custom badges we MUST provide a badge for each level! Failure to do so will not discard the custom badges, they won't even be saved.

**Comment by alymanbuttler** [comment]
OK, thank you--I will try to figure out why this is happening & update here if I do.

**Comment by alymanbuttler** [comment]
I deleted all the images I had uploaded. Then, I uploaded new, different images. This fixed it--teachers and students can both see the custom badges now.

Merci!
Andrew

**Comment by FMCorz** [comment]
I wonder what went wrong initially. Thanks!
