### ISSUE TITLE
rename config.php to settings.php

### ISSUE THREAD

**Issue by js0000** [FMCorz/moodle-block_xp#68]
since main moodle configuration file is named 'config.php' i have a rule in my webserver to prevent files of that name from being returned to users. this is probably a good idea for any php web application.
however, i would have to open up a part of the webserver config in order to properly use this plugin. i'd like to suggest that the config.php file is renamed to settings.php since that is also the display tab name for this set of options. and this way, my web server's security configuration is easier.

xp is great- keep up the good work!

**Comment by FMCorz** [comment]
Hi,

Thanks for the suggestion. I wanted to name it `settings.php`, but the latter is reserved for admin settings, so I picked `config.php` instead. I will keep your issue in mind and see how I can help.

Cheers,
Fred

**Comment by js0000** [comment]
so many reserved words ... so few options ...

configuration.php
xpsettings.php

nothing obvious comes to my mind- thx for taking my concerns into consideration.

**Comment by FMCorz** [comment]
Thanks for your valuable suggestions.

This issue should have been solved with the release of v3.0.
