### ISSUE TITLE
No easy way to set up initial XP

### ISSUE THREAD

**Issue by mudrd8mz** [FMCorz/moodle-block_xp#7]
In my case, I needed to set up some initial experience points to participants as they did not start from zero. There is currently no UI to do it. The participant must have at least one XP to be shown in the report. I learnt I can do it by passing the different userid manually to report.php. It would help if the report displayed all enrolled students with the ability to edit their XP.

**Comment by FMCorz** [comment]
I agree, some of the screens should display all the enrolled users, however that was the easy I found to only account the users that had relevant XP. Before I think that admins and teachers were included in the XP thing, which was a bit problematic. Now there is a capability that controls who can earn XP over the course, only those users should be displayed in the ladder and report. That makes the query a bit more complex ;)...
