### ISSUE TITLE
Not possible to reward students for completing a course

### ISSUE THREAD

**Issue by davosmith** [FMCorz/moodle-block_xp#70]
There does not seem to be a way to reward students for completing a course.

You can enter '\core\event\course_completed' as the event to catch, but due to course completion being processed by cron, the correct userid in this case is $event->relateduserid, not $event->userid, so the code never makes it through the initial background checks (in block_xp_helper::observer) and into the part that checks if the event is relevant.

**Comment by FMCorz** [comment]
Thanks for the report.

Indeed, by design the block only rewards for events which occur as the students perform actions, not when they are deferred. However, I'm working on something which should make it possible.

**Comment by kineoalex** [comment]
Hi @FMCorz, we've come across the same issue as well. Do you have any idea on when you might have an update to address it?
Many thanks!

**Comment by FMCorz** [comment]
Hopefully soon.

**Comment by FMCorz** [comment]
This feature is now available through the add-on [Level up! Plus](https://github.com/FMCorz/moodle-local_xp).
