### ISSUE TITLE
Rule that match a component by type

### ISSUE THREAD

**Issue by Canx** [FMCorz/moodle-block_xp#75]
Hi, I would need this specifically in Level Up Plus to combine with a "Completed activity" event rule in order to filter them by component (questionary, task, workshop...), as currently there is no "Completed <type of component> activity" option.

Now I can combine with a concrete component rule, but that would mean to add every new activity to the rule.

**Comment by FMCorz** [comment]
Good suggestion, I've had that in mind as well. In the mean time, the workaround is:

    Event property [Name] contains [mod_assign/]

Where `mod_assign/` is replaced with the full name of other components: `mod_quiz/`, `mod_workship/`...

**Comment by Canx** [comment]
Thanks Fred! This will solve it perfectly for now.

**Comment by FMCorz** [comment]
Closing this as an additional rule for targeting the component itself does not seem to be requested by more users, and would generally be advanced enough for educators to use the above workaround.
