### ISSUE TITLE
No clear instructions on how to ignore all events but one

### ISSUE THREAD

**Issue by mudrd8mz** [FMCorz/moodle-block_xp#8]
In my case, I want to watch only the event `\mod_stampcoll\event\stamp_granted`, assign it 1 XP and nothing else. After some testing, I learnt the only way to exclude all other events from processing is to define the second rule: Event name contains "event" => 0

Is this correct way? If so, it might be worth of adding into the plugin docs.

The other thing I noticed: before I added this "any event" rule, I tried to override the default rules based on the CRUD value. So I had my stampcoll related rule followed by four CRUD rules (Event CRUD is equal to {c,r,u,d} => 0). However, this did not seem to work. Events like course_viewed (IIRC) still gave default 9 XP as if my CRUD rules were ignored. Is it possible to provide more docs on event rules processing?

**Comment by FMCorz** [comment]
I never thought of a rule to ignore everything but I guess your workaround works fine. I might need to add negative rules. The rule API supports a lot of different options but only two are exposed in the UI. I will have a look at the CRUD issue that you mention. Thanks!

**Comment by FMCorz** [comment]
The CRUD thing seemed to work for me.

**Comment by FMCorz** [comment]
I have revamped the screen, there is still no indications on how to filter out everything but could you have a look and see if you can find a way that works for you?

**Comment by mudrd8mz** [comment]
Will look at this next week when working on 3.0 upgrade of the site we use this plugin at. Thanks Fred.

**Comment by FMCorz** [comment]
I'll be closing this now. There is still nothing that explains how to ignore all events but reverting the rules displayed in the defaults should be enough. Please reopen this issue if it turns out to be a blocker.

**Comment by mudrd8mz** [comment]
For the reference just in case it helps someone else in the future, this is how my rules setting page looks like:

![screenshot_2016-02-15_10-41-50](https://cloud.githubusercontent.com/assets/85831/13044888/d3c51908-d3d0-11e5-9a53-b26047bd7ef1.png)

**Comment by FMCorz** [comment]
Thanks David!
