### ISSUE TITLE
Laddder Labels and descitpion

### ISSUE THREAD

**Issue by behoof** [FMCorz/moodle-block_xp#82]
I'm putting a label and  desciption of the level in your description field. 

Example: 

Sensei<br>You have started a lifelong learning....

But, the field is very very narrow. Please extend the field length and add a label

Bert

**Comment by FMCorz** [comment]
Thanks for the report. We are working on revamping this screen entirely. Other priorities have gotten in the way of this but hopefully we can tackle this soon. Thanks.

See: https://twitter.com/BranchUpTech/status/936084199798214657
