### ISSUE TITLE
Error Code: codingerror

### ISSUE THREAD

**Issue by sadawie** [FMCorz/moodle-block_xp#83]
we are using Nginx and it's properly configured for Moodle 3.4, we were able to install the plugin but when we attempt to edit settings, access report, ladder or info of the block at the course level we get
"Coding error detected, it must be fixed by a programmer: Controller for route not found."
although it worked when we disabled "slasharguments" in the Moodle admin settings. unfortunately we can't keep this disabled. 
![2018-04-02 09_18_12-error](https://user-images.githubusercontent.com/29485489/38197960-b2ef355a-3658-11e8-8f0a-f307df0445c5.png)

**Comment by FMCorz** [comment]
Thanks for the report. Your nginx configuration must have an issue, please refer to this issue where a similar problem was resolved: https://github.com/FMCorz/moodle-block_xp/issues/79. Thanks!
