### ISSUE TITLE
When restored inside a course backup, block XP is disabled

### ISSUE THREAD

**Issue by santimoral** [FMCorz/moodle-block_xp#9]
When you restore a course backup including de Level Up block, this is disabled. So the course is not exactly restored in its last state. If you use a template course to create new courses, you have to activate the block every time.

**Comment by FMCorz** [comment]
Thanks for reporting this bug. I guess all other options are also lost when you restore, that would be caused by the fact that I forgot to add all the code required for backups and restore. I will try to get onto that shortly. Thanks for your interest :)

**Comment by santimoral** [comment]
Thank you very much for your answer. Congratulations again for your great job!
