### ISSUE TITLE
Invalid config requested: enablegroupladder

### ISSUE THREAD

**Issue by aguatacuperche** [FMCorz/moodle-block_xp#90]
Hi, on Moodle 3.5.2+

Debug info: 
Error code: codingerror
Stack trace:
line 70 of /blocks/xp/classes/local/config/config_stack.php: coding_exception thrown
line 185 of /local/xp/classes/local/block/course_block.php: call to block_xp\local\config\config_stack->get()
line 176 of /blocks/xp/classes/local/block/course_block.php: call to local_xp\local\block\course_block->get_block_navigation()
line 163 of /local/xp/classes/local/block/course_block.php: call to block_xp\local\block\course_block->get_content()
line 288 of /blocks/moodleblock.class.php: call to local_xp\local\block\course_block->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1211 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1263 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 374 of /lib/blocklib.php: call to block_manager->ensure_content_created()
line 3939 of /lib/outputrenderers.php: call to block_manager->region_has_content()
line 47 of /theme/boost_campus/layout/columns2.php: call to core_renderer->blocks()
line 1287 of /lib/outputrenderers.php: call to include()
line 1217 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 244 of /course/view.php: call to core_renderer->header()

**Comment by FMCorz** [comment]
Thanks for the report. This bug seems to be caused by Level up! Plus, could you please contact us at `level at branchup dot tech` stating which version of Level up!, and Level up! Plus you are using? Thank you!

**Comment by FMCorz** [comment]
This may also be due to forgetting to upgrading your site after installing the plugin.
