### ISSUE TITLE
Progress Bars do not display properly

### ISSUE THREAD

**Issue by gjrogala** [FMCorz/moodle-block_xp#91]
Hi

The progress bar in both the Badge block as well as the Ladder section do not fill (they look empty) even though students have XP awarded (see screenshots below). Is there a fix for this coming? 

![a2](https://user-images.githubusercontent.com/44284542/49357781-52c2d000-f70b-11e8-870f-b15957a51407.png)

![a](https://user-images.githubusercontent.com/44284542/49357859-9cabb600-f70b-11e8-90ac-b4e8a9d5c537.png)

Thanks!

**Comment by FMCorz** [comment]
Hi @gjrogala,

I see you're using Level up! Plus. Could you please email us at levelup@branchup.tech mentioning which version of Level up! Plus you are using, as well the Moodle version and importantly, the theme being selected.

Thanks!
Fred

**Comment by gjrogala** [comment]
Sure thing! Thanks for a quick response.

**Comment by FMCorz** [comment]
This was resolved by upgrading to the latest versions.
