### ISSUE TITLE
data-aria-autofocus is causing page to jump

### ISSUE THREAD

**Issue by sharpchi** [FMCorz/moodle-block_xp#99]
Using M3.6 and Boost with v3.7 of your plugin, we're finding that the page is scrolling down on page load (as if it was going to a bookmark). I think it's to do with the data-aria-autofocus property on the blue alert-info box.
![image](https://user-images.githubusercontent.com/3774280/66037330-3ea45680-e507-11e9-9fc1-3c05601d0a8c.png)
To test add a few blocks above the XP block to push it below the cut. Turn off editing and reload the page.
If I empty the Introduction setting (block_xp | description) the page doesn't jump.

**Comment by FMCorz** [comment]
Thank you for your report @sharpchi, we had not noticed this. This seems to be part of recent changes in Moodle to improve accessibility. Level up! uses this Moodle component to maintain UI consistency and facilitate theming. We will look at fixing this issue.
